// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class AuthMessage;
@class AuthMessageBuilder;
@class Capability;
@class CapabilityBuilder;
@class IQMessage;
@class IQMessageBuilder;
@class MessageBody;
@class MessageBodyBuilder;
@class MessageKeyValue;
@class MessageKeyValueBuilder;
@class PackageLength;
@class PackageLengthBuilder;
@class PresenceMessage;
@class PresenceMessageBuilder;
@class ProceedTLS;
@class ProceedTLSBuilder;
@class ProtoHeader;
@class ProtoHeaderBuilder;
@class ProtoMessage;
@class ProtoMessageBuilder;
@class ResponseFailure;
@class ResponseFailureBuilder;
@class ResponseSucceeded;
@class ResponseSucceededBuilder;
@class StartTLS;
@class StartTLSBuilder;
@class StreamBegin;
@class StreamBeginBuilder;
@class StreamEnd;
@class StreamEndBuilder;
@class StringHeader;
@class StringHeaderBuilder;
@class UserConnect;
@class UserConnectBuilder;
@class WelcomeMessage;
@class WelcomeMessageBuilder;
@class XmppMessage;
@class XmppMessageBuilder;


typedef NS_ENUM(SInt32, SignalType) {
  SignalTypeSignalTypePresence = 1,
  SignalTypeSignalTypeIq = 2,
  SignalTypeSignalTypeIqresponse = 3,
  SignalTypeSignalTypeSucceededResponse = 4,
  SignalTypeSignalTypeFailureResponse = 5,
  SignalTypeSignalTypeChat = 6,
  SignalTypeSignalTypeGroupChat = 7,
  SignalTypeSignalTypeNormal = 8,
  SignalTypeSignalTypeError = 9,
  SignalTypeSignalTypeTyping = 10,
  SignalTypeSignalTypeNote = 11,
  SignalTypeSignalTypeTransfor = 12,
  SignalTypeSignalTypeReadmark = 13,
  SignalTypeSignalTypeRevoke = 14,
  SignalTypeSignalTypeSubscription = 15,
  SignalTypeSignalTypeMstate = 16,
  SignalTypeSignalTypeHeadline = 17,
  SignalTypeSignalTypeShareLocation = 20,
  SignalTypeSignalTypeHeartBeat = 30,
  SignalTypeSignalTypeAuth = 45,
  SignalTypeSignalTypeStreamBegin = 50,
  SignalTypeSignalTypeStreamEnd = 51,
  SignalTypeSignalTypeWelcome = 100,
  SignalTypeSignalTypeUserConnect = 101,
  SignalTypeSignalTypeChallenge = 102,
  SignalTypeSignalStartTls = 106,
  SignalTypeSignalProceedTls = 108,
  SignalTypeSignalTypeWebRtc = 110,
  SignalTypeSignalTypeCarbon = 128,
  SignalTypeSignalTypeConsult = 132,
  SignalTypeSignalTypeEncryption = 136,
  SignalTypeSignalTypeCollection = 140,
  SignalTypeSignalTypeTrans = 141,
};

BOOL SignalTypeIsValidValue(SignalType value);
NSString *NSStringFromSignalType(SignalType value);

typedef NS_ENUM(SInt32, ClientType) {
  ClientTypeClientTypeMac = 1,
  ClientTypeClientTypeiOs = 2,
  ClientTypeClientTypePc = 3,
  ClientTypeClientTypeAndroid = 4,
  ClientTypeClientTypeLinux = 5,
  ClientTypeClientTypeWeb = 6,
};

BOOL ClientTypeIsValidValue(ClientType value);
NSString *NSStringFromClientType(ClientType value);

typedef NS_ENUM(SInt32, MessageType) {
  MessageTypeMessageTypePnote = -11,
  MessageTypeMessageTypeRevoke = -1,
  MessageTypeMessageTypeConsultRevoke = -2,
  MessageTypeMessageTypeText = 1,
  MessageTypeMessageTypeVoice = 2,
  MessageTypeMessageTypePhoto = 3,
  MessageTypeMessageTypeSogouIcon = 4,
  MessageTypeMessageTypeFile = 5,
  MessageTypeMessageTypeTopic = 6,
  MessageTypeMessageTypeRichText = 7,
  MessageTypeMessageTypeActionRichText = 8,
  MessageTypeMessageTypeReply = 9,
  MessageTypeMessageTypeShock = 10,
  MessageTypeMessageTypeNote = 11,
  MessageTypeMessageTypeGroupAt = 12,
  MessageTypeMessageTypeMarkdown = 13,
  MessageTypeMessageTypeExtText = 14,
  MessageTypeMessageTypeGroupNotify = 15,
  MessageTypeMessageTypeLocalShare = 16,
  MessageTypeMessageTypeWebRtcaudio = 20,
  MessageTypeMessageTypeWebRtcvidio = 21,
  MessageTypeMessageTypeImageNew = 30,
  MessageTypeMessageTypeSmallVideo = 32,
  MessageTypeMessageTypeRobotAnswer = 47,
  MessageTypeMessageTypeSourceCode = 64,
  MessageTypeMessageTypeTime = 101,
  MessageTypeMessageTypeBurnAfterRead = 128,
  MessageTypeMessageTypeCardShare = 256,
  MessageTypeMessageTypeMeetingRemind = 257,
  MessageTypeMessageTypeWorkWorldAtRemind = 258,
  MessageTypeMessageTypeEncrypt = 404,
  MessageTypeMessageTypeActivity = 511,
  MessageTypeMessageTypeRedPack = 512,
  MessageTypeMessageTypeAa = 513,
  MessageTypeMessageTypeCommonTrdInfo = 666,
  MessageTypeMessageTypeCommonProductInfo = 888,
  MessageTypeMessageTypeTransChatToCustomer = 1001,
  MessageTypeMessageTypeTransChatToCustomerFeedback = 1003,
  MessageTypeMessageTypeTransChatToCustomerService = 1002,
  MessageTypeMessageTypeTransChatToCustomerServiceFeedback = 1004,
  MessageTypeMessageTypeRedPackInfo = 1024,
  MessageTypeMessageTypeAainfo = 1025,
  MessageTypeMessageTypeConsult = 2001,
  MessageTypeMessageTypeConsultResult = 2002,
  MessageTypeMessageTypeGrabMenuVcard = 2003,
  MessageTypeMessageTypeGrabMenuResult = 2004,
  MessageTypeMessageTypeQczhongbao = 2005,
  MessageTypeMessageTypeMicroTourGuide = 3001,
  MessageTypeMessageTypeProduct = 4096,
  MessageTypeWebRtcMsgTypeVideoMeeting = 5001,
  MessageTypeMessageTypeShareLocation = 8192,
  MessageTypeMessageTypeTransNormal = 10081,
  MessageTypeWebRtcMsgTypeLive = 65501,
  MessageTypeWebRtcMsgTypeVideoCall = 65505,
  MessageTypeWebRtcMsgTypeAudioCall = 65506,
  MessageTypeWebRtcMsgTypeVideoGroup = 65534,
  MessageTypeWebRtcMsgTypeVideo = 65535,
  MessageTypeMessageTypeRobotQuestionList = 65536,
  MessageTypeMessageTypeRobotTurnToUser = 65537,
  MessageTypeMessageTypeRobotQuestionListNew = 65538,
  MessageTypeMessageTypeFlightRemind = 65550,
  MessageTypeMessageTypeCommonServiceCard = 65551,
  MessageTypeWebRtcMsgTypeAudio = 131072,
  MessageTypeMessageTypeNotice = 134217728,
  MessageTypeMessageTypeSystem = 268435456,
  MessageTypeMediaTypeSystemLy = 268435457,
};

BOOL MessageTypeIsValidValue(MessageType value);
NSString *NSStringFromMessageType(MessageType value);

typedef NS_ENUM(SInt32, StringHeaderType) {
  StringHeaderTypeStringHeaderTypeChatId = 1,
  StringHeaderTypeStringHeaderTypeChannelId = 2,
  StringHeaderTypeStringHeaderTypeExtendInfo = 3,
  StringHeaderTypeStringHeaderTypeBackupInfo = 4,
  StringHeaderTypeStringHeaderTypeReadType = 5,
  StringHeaderTypeStringHeaderTypeJid = 7,
  StringHeaderTypeStringHeaderTypeRealJid = 8,
  StringHeaderTypeStringHeaderTypeInviteJid = 9,
  StringHeaderTypeStringHeaderTypeDeleleJid = 10,
  StringHeaderTypeStringHeaderTypeNick = 12,
  StringHeaderTypeStringHeaderTypeTitle = 16,
  StringHeaderTypeStringHeaderTypePic = 18,
  StringHeaderTypeStringHeaderTypeVersion = 20,
  StringHeaderTypeStringHeaderTypeMethod = 22,
  StringHeaderTypeStringHeaderTypeBody = 24,
  StringHeaderTypeStringHeaderTypeAffiliation = 28,
  StringHeaderTypeStringHeaderTypeType = 30,
  StringHeaderTypeStringHeaderTypeResult = 32,
  StringHeaderTypeStringHeaderTypeReason = 34,
  StringHeaderTypeStringHeaderTypeRole = 36,
  StringHeaderTypeStringHeaderTypeDomain = 38,
  StringHeaderTypeStringHeaderTypeStatus = 40,
  StringHeaderTypeStringHeaderTypeCode = 42,
  StringHeaderTypeStringHeaderTypeCdata = 50,
  StringHeaderTypeStringHeaderTypeTimeValue = 52,
  StringHeaderTypeStringHeaderTypeKeyValue = 54,
  StringHeaderTypeStringHeaderTypeName = 56,
  StringHeaderTypeStringHeaderTypeHost = 58,
  StringHeaderTypeStringHeaderTypeQuestion = 60,
  StringHeaderTypeStringHeaderTypeAnswer = 62,
  StringHeaderTypeStringHeaderTypeFriends = 64,
  StringHeaderTypeStringHeaderTypeValue = 66,
  StringHeaderTypeStringHeaderTypeMaskedUuser = 68,
  StringHeaderTypeStringHeaderTypeKey = 70,
  StringHeaderTypeStringHeaderTypeCarbon = 72,
  StringHeaderTypeStringHeaderTypeMode = 76,
};

BOOL StringHeaderTypeIsValidValue(StringHeaderType value);
NSString *NSStringFromStringHeaderType(StringHeaderType value);

typedef NS_ENUM(SInt32, IQMessageKeyType) {
  IQMessageKeyTypeIqkeyBind = 1,
  IQMessageKeyTypeIqkeyMucCreate = 2,
  IQMessageKeyTypeIqkeyMucCreateV2 = 3,
  IQMessageKeyTypeIqkeyMucInviteV2 = 4,
  IQMessageKeyTypeIqkeyGetMucUser = 5,
  IQMessageKeyTypeIqkeySetMucUser = 6,
  IQMessageKeyTypeIqkeyDelMucUser = 7,
  IQMessageKeyTypeIqkeyAddUserSubscribe = 8,
  IQMessageKeyTypeIqkeyDelUserSubscribe = 9,
  IQMessageKeyTypeIqkeyGetUserSubScribe = 10,
  IQMessageKeyTypeIqkeyGetVerifyFriendOpt = 11,
  IQMessageKeyTypeIqkeySetVerifyFriendOpt = 12,
  IQMessageKeyTypeIqkeySetUserSubScribeV2 = 13,
  IQMessageKeyTypeIqkeyGetUserSubScribeV2 = 14,
  IQMessageKeyTypeIqkeyGetUserFriend = 16,
  IQMessageKeyTypeIqkeyDelUserFriend = 18,
  IQMessageKeyTypeIqkeyGetUserKey = 20,
  IQMessageKeyTypeIqkeyGetUserMask = 22,
  IQMessageKeyTypeIqkeySetUserMask = 24,
  IQMessageKeyTypeIqkeyCancelUserMask = 26,
  IQMessageKeyTypeIqkeySetAdmin = 28,
  IQMessageKeyTypeIqkeySetMember = 30,
  IQMessageKeyTypeIqkeyCancelMember = 32,
  IQMessageKeyTypeIqkeyGetUserMucs = 36,
  IQMessageKeyTypeIqkeyDestroyMuc = 40,
  IQMessageKeyTypeIqkeyPing = 50,
  IQMessageKeyTypeIqkeyAddPush = 52,
  IQMessageKeyTypeIqkeyCancelPush = 60,
  IQMessageKeyTypeIqkeyResult = 80,
  IQMessageKeyTypeIqkeyError = 90,
  IQMessageKeyTypeIqkeyGetVuser = 92,
  IQMessageKeyTypeIqkeyGetVuserRole = 94,
  IQMessageKeyTypeIqkeyStartSession = 96,
  IQMessageKeyTypeIqkeyEndSession = 98,
  IQMessageKeyTypeIqkeySessionEvent = 99,
};

BOOL IQMessageKeyTypeIsValidValue(IQMessageKeyType value);
NSString *NSStringFromIQMessageKeyType(IQMessageKeyType value);

typedef NS_ENUM(SInt32, StreamEndCode) {
  StreamEndCodeStreamEndCodeReloginBase = 100,
  StreamEndCodeStreamEndCodeReloginFromNav = 101,
  StreamEndCodeStreamEndCodeNoReloginBase = 200,
};

BOOL StreamEndCodeIsValidValue(StreamEndCode value);
NSString *NSStringFromStreamEndCode(StreamEndCode value);

typedef NS_ENUM(SInt32, CategoryType) {
  CategoryTypeCategoryOrganizational = 1,
  CategoryTypeCategorySessionList = 2,
  CategoryTypeCategoryNavigation = 3,
  CategoryTypeCategoryOpsnotification = 4,
  CategoryTypeCategoryConfigSync = 6,
  CategoryTypeCategoryMsgNotify = 7,
  CategoryTypeCategoryCalendarSync = 8,
  CategoryTypeCategoryOnlineClientSync = 9,
  CategoryTypeCategoryAskLog = 10,
  CategoryTypeCategoryClientSpecialNotice = 11,
  CategoryTypeCategoryTickUser = 100,
  CategoryTypeCategoryGlobalNotification = 98,
  CategoryTypeCategorySpecifyNotification = 99,
  CategoryTypeCategoryWorkWorldNotice = 12,
  CategoryTypeCategoryHotLineSync = 13,
};

BOOL CategoryTypeIsValidValue(CategoryType value);
NSString *NSStringFromCategoryType(CategoryType value);

typedef NS_ENUM(SInt32, PresenceKeyType) {
  PresenceKeyTypePresenceKeyPriority = 1,
  PresenceKeyTypePresenceKeyVerifyFriend = 2,
  PresenceKeyTypePresenceKeyManualAuthenticationConfirm = 3,
  PresenceKeyTypePresenceKeyResult = 6,
  PresenceKeyTypePresenceKeyNotify = 7,
  PresenceKeyTypePresenceKeyError = 8,
};

BOOL PresenceKeyTypeIsValidValue(PresenceKeyType value);
NSString *NSStringFromPresenceKeyType(PresenceKeyType value);


@interface MessageRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define MessageKeyValue_key @"key"
#define MessageKeyValue_value @"value"
@interface MessageKeyValue : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasKey_:1;
  BOOL hasValue_:1;
  NSString* key;
  NSString* value;
}
- (BOOL) hasKey;
- (BOOL) hasValue;
@property (readonly, strong) NSString* key;
@property (readonly, strong) NSString* value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageKeyValueBuilder*) builder;
+ (MessageKeyValueBuilder*) builder;
+ (MessageKeyValueBuilder*) builderWithPrototype:(MessageKeyValue*) prototype;
- (MessageKeyValueBuilder*) toBuilder;

+ (MessageKeyValue*) parseFromData:(NSData*) data;
+ (MessageKeyValue*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageKeyValue*) parseFromInputStream:(NSInputStream*) input;
+ (MessageKeyValue*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageKeyValue*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageKeyValue*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageKeyValueBuilder : PBGeneratedMessageBuilder {
@private
  MessageKeyValue* resultMessageKeyValue;
}

- (MessageKeyValue*) defaultInstance;

- (MessageKeyValueBuilder*) clear;
- (MessageKeyValueBuilder*) clone;

- (MessageKeyValue*) build;
- (MessageKeyValue*) buildPartial;

- (MessageKeyValueBuilder*) mergeFrom:(MessageKeyValue*) other;
- (MessageKeyValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageKeyValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasKey;
- (NSString*) key;
- (MessageKeyValueBuilder*) setKey:(NSString*) value;
- (MessageKeyValueBuilder*) clearKey;

- (BOOL) hasValue;
- (NSString*) value;
- (MessageKeyValueBuilder*) setValue:(NSString*) value;
- (MessageKeyValueBuilder*) clearValue;
@end

#define StringHeader_params @"params"
#define StringHeader_key @"key"
#define StringHeader_value @"value"
#define StringHeader_definedKey @"definedKey"
@interface StringHeader : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasKey_:1;
  BOOL hasValue_:1;
  BOOL hasDefinedKey_:1;
  NSString* key;
  NSString* value;
  StringHeaderType definedKey;
  NSMutableArray * paramsArray;
}
- (BOOL) hasKey;
- (BOOL) hasValue;
- (BOOL) hasDefinedKey;
@property (readonly, strong) NSArray<MessageKeyValue*> * params;
@property (readonly, strong) NSString* key;
@property (readonly, strong) NSString* value;
@property (readonly) StringHeaderType definedKey;
- (MessageKeyValue*)paramsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (StringHeaderBuilder*) builder;
+ (StringHeaderBuilder*) builder;
+ (StringHeaderBuilder*) builderWithPrototype:(StringHeader*) prototype;
- (StringHeaderBuilder*) toBuilder;

+ (StringHeader*) parseFromData:(NSData*) data;
+ (StringHeader*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StringHeader*) parseFromInputStream:(NSInputStream*) input;
+ (StringHeader*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StringHeader*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (StringHeader*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface StringHeaderBuilder : PBGeneratedMessageBuilder {
@private
  StringHeader* resultStringHeader;
}

- (StringHeader*) defaultInstance;

- (StringHeaderBuilder*) clear;
- (StringHeaderBuilder*) clone;

- (StringHeader*) build;
- (StringHeader*) buildPartial;

- (StringHeaderBuilder*) mergeFrom:(StringHeader*) other;
- (StringHeaderBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (StringHeaderBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray<MessageKeyValue*> *)params;
- (MessageKeyValue*)paramsAtIndex:(NSUInteger)index;
- (StringHeaderBuilder *)addParams:(MessageKeyValue*)value;
- (StringHeaderBuilder *)setParamsArray:(NSArray<MessageKeyValue*> *)array;
- (StringHeaderBuilder *)clearParams;

- (BOOL) hasKey;
- (NSString*) key;
- (StringHeaderBuilder*) setKey:(NSString*) value;
- (StringHeaderBuilder*) clearKey;

- (BOOL) hasValue;
- (NSString*) value;
- (StringHeaderBuilder*) setValue:(NSString*) value;
- (StringHeaderBuilder*) clearValue;

- (BOOL) hasDefinedKey;
- (StringHeaderType) definedKey;
- (StringHeaderBuilder*) setDefinedKey:(StringHeaderType) value;
- (StringHeaderBuilder*) clearDefinedKey;
@end

#define PackageLength_length @"length"
@interface PackageLength : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLength_:1;
  SInt32 length;
}
- (BOOL) hasLength;
@property (readonly) SInt32 length;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PackageLengthBuilder*) builder;
+ (PackageLengthBuilder*) builder;
+ (PackageLengthBuilder*) builderWithPrototype:(PackageLength*) prototype;
- (PackageLengthBuilder*) toBuilder;

+ (PackageLength*) parseFromData:(NSData*) data;
+ (PackageLength*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PackageLength*) parseFromInputStream:(NSInputStream*) input;
+ (PackageLength*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PackageLength*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PackageLength*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PackageLengthBuilder : PBGeneratedMessageBuilder {
@private
  PackageLength* resultPackageLength;
}

- (PackageLength*) defaultInstance;

- (PackageLengthBuilder*) clear;
- (PackageLengthBuilder*) clone;

- (PackageLength*) build;
- (PackageLength*) buildPartial;

- (PackageLengthBuilder*) mergeFrom:(PackageLength*) other;
- (PackageLengthBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PackageLengthBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLength;
- (SInt32) length;
- (PackageLengthBuilder*) setLength:(SInt32) value;
- (PackageLengthBuilder*) clearLength;
@end

#define ProtoHeader_version @"version"
#define ProtoHeader_options @"options"
#define ProtoHeader_optionlist @"optionlist"
#define ProtoHeader_length @"length"
#define ProtoHeader_content @"content"
#define ProtoHeader_message @"message"
@interface ProtoHeader : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasVersion_:1;
  BOOL hasOptions_:1;
  BOOL hasLength_:1;
  BOOL hasContent_:1;
  BOOL hasMessage_:1;
  SInt32 version;
  SInt32 options;
  SInt32 length;
  NSString* content;
  NSData* message;
  PBAppendableArray * optionlistArray;
}
- (BOOL) hasVersion;
- (BOOL) hasOptions;
- (BOOL) hasLength;
- (BOOL) hasContent;
- (BOOL) hasMessage;
@property (readonly) SInt32 version;
@property (readonly) SInt32 options;
@property (readonly, strong) PBArray * optionlist;
@property (readonly) SInt32 length;
@property (readonly, strong) NSString* content;
@property (readonly, strong) NSData* message;
- (SInt32)optionlistAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtoHeaderBuilder*) builder;
+ (ProtoHeaderBuilder*) builder;
+ (ProtoHeaderBuilder*) builderWithPrototype:(ProtoHeader*) prototype;
- (ProtoHeaderBuilder*) toBuilder;

+ (ProtoHeader*) parseFromData:(NSData*) data;
+ (ProtoHeader*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtoHeader*) parseFromInputStream:(NSInputStream*) input;
+ (ProtoHeader*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtoHeader*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtoHeader*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtoHeaderBuilder : PBGeneratedMessageBuilder {
@private
  ProtoHeader* resultProtoHeader;
}

- (ProtoHeader*) defaultInstance;

- (ProtoHeaderBuilder*) clear;
- (ProtoHeaderBuilder*) clone;

- (ProtoHeader*) build;
- (ProtoHeader*) buildPartial;

- (ProtoHeaderBuilder*) mergeFrom:(ProtoHeader*) other;
- (ProtoHeaderBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtoHeaderBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasVersion;
- (SInt32) version;
- (ProtoHeaderBuilder*) setVersion:(SInt32) value;
- (ProtoHeaderBuilder*) clearVersion;

- (BOOL) hasOptions;
- (SInt32) options;
- (ProtoHeaderBuilder*) setOptions:(SInt32) value;
- (ProtoHeaderBuilder*) clearOptions;

- (PBAppendableArray *)optionlist;
- (SInt32)optionlistAtIndex:(NSUInteger)index;
- (ProtoHeaderBuilder *)addOptionlist:(SInt32)value;
- (ProtoHeaderBuilder *)setOptionlistArray:(NSArray *)array;
- (ProtoHeaderBuilder *)setOptionlistValues:(const SInt32 *)values count:(NSUInteger)count;
- (ProtoHeaderBuilder *)clearOptionlist;

- (BOOL) hasLength;
- (SInt32) length;
- (ProtoHeaderBuilder*) setLength:(SInt32) value;
- (ProtoHeaderBuilder*) clearLength;

- (BOOL) hasContent;
- (NSString*) content;
- (ProtoHeaderBuilder*) setContent:(NSString*) value;
- (ProtoHeaderBuilder*) clearContent;

- (BOOL) hasMessage;
- (NSData*) message;
- (ProtoHeaderBuilder*) setMessage:(NSData*) value;
- (ProtoHeaderBuilder*) clearMessage;
@end

#define AuthMessage_mechanism @"mechanism"
#define AuthMessage_method @"method"
#define AuthMessage_msgId @"msgId"
#define AuthMessage_authKey @"authKey"
#define AuthMessage_otherBody @"otherBody"
@interface AuthMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMechanism_:1;
  BOOL hasMethod_:1;
  BOOL hasMsgId_:1;
  BOOL hasAuthKey_:1;
  BOOL hasOtherBody_:1;
  NSString* mechanism;
  NSString* method;
  NSString* msgId;
  NSString* authKey;
  MessageBody* otherBody;
}
- (BOOL) hasMechanism;
- (BOOL) hasMethod;
- (BOOL) hasMsgId;
- (BOOL) hasAuthKey;
- (BOOL) hasOtherBody;
@property (readonly, strong) NSString* mechanism;
@property (readonly, strong) NSString* method;
@property (readonly, strong) NSString* msgId;
@property (readonly, strong) NSString* authKey;
@property (readonly, strong) MessageBody* otherBody;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AuthMessageBuilder*) builder;
+ (AuthMessageBuilder*) builder;
+ (AuthMessageBuilder*) builderWithPrototype:(AuthMessage*) prototype;
- (AuthMessageBuilder*) toBuilder;

+ (AuthMessage*) parseFromData:(NSData*) data;
+ (AuthMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthMessage*) parseFromInputStream:(NSInputStream*) input;
+ (AuthMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AuthMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AuthMessageBuilder : PBGeneratedMessageBuilder {
@private
  AuthMessage* resultAuthMessage;
}

- (AuthMessage*) defaultInstance;

- (AuthMessageBuilder*) clear;
- (AuthMessageBuilder*) clone;

- (AuthMessage*) build;
- (AuthMessage*) buildPartial;

- (AuthMessageBuilder*) mergeFrom:(AuthMessage*) other;
- (AuthMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AuthMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMechanism;
- (NSString*) mechanism;
- (AuthMessageBuilder*) setMechanism:(NSString*) value;
- (AuthMessageBuilder*) clearMechanism;

- (BOOL) hasMethod;
- (NSString*) method;
- (AuthMessageBuilder*) setMethod:(NSString*) value;
- (AuthMessageBuilder*) clearMethod;

- (BOOL) hasMsgId;
- (NSString*) msgId;
- (AuthMessageBuilder*) setMsgId:(NSString*) value;
- (AuthMessageBuilder*) clearMsgId;

- (BOOL) hasAuthKey;
- (NSString*) authKey;
- (AuthMessageBuilder*) setAuthKey:(NSString*) value;
- (AuthMessageBuilder*) clearAuthKey;

- (BOOL) hasOtherBody;
- (MessageBody*) otherBody;
- (AuthMessageBuilder*) setOtherBody:(MessageBody*) value;
- (AuthMessageBuilder*) setOtherBodyBuilder:(MessageBodyBuilder*) builderForValue;
- (AuthMessageBuilder*) mergeOtherBody:(MessageBody*) value;
- (AuthMessageBuilder*) clearOtherBody;
@end

#define WelcomeMessage_domain @"domain"
#define WelcomeMessage_version @"version"
#define WelcomeMessage_user @"user"
#define WelcomeMessage_sockmod @"sockmod"
@interface WelcomeMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasDomain_:1;
  BOOL hasVersion_:1;
  BOOL hasUser_:1;
  BOOL hasSockmod_:1;
  NSString* domain;
  NSString* version;
  NSString* user;
  NSString* sockmod;
}
- (BOOL) hasDomain;
- (BOOL) hasVersion;
- (BOOL) hasUser;
- (BOOL) hasSockmod;
@property (readonly, strong) NSString* domain;
@property (readonly, strong) NSString* version;
@property (readonly, strong) NSString* user;
@property (readonly, strong) NSString* sockmod;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (WelcomeMessageBuilder*) builder;
+ (WelcomeMessageBuilder*) builder;
+ (WelcomeMessageBuilder*) builderWithPrototype:(WelcomeMessage*) prototype;
- (WelcomeMessageBuilder*) toBuilder;

+ (WelcomeMessage*) parseFromData:(NSData*) data;
+ (WelcomeMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (WelcomeMessage*) parseFromInputStream:(NSInputStream*) input;
+ (WelcomeMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (WelcomeMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (WelcomeMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface WelcomeMessageBuilder : PBGeneratedMessageBuilder {
@private
  WelcomeMessage* resultWelcomeMessage;
}

- (WelcomeMessage*) defaultInstance;

- (WelcomeMessageBuilder*) clear;
- (WelcomeMessageBuilder*) clone;

- (WelcomeMessage*) build;
- (WelcomeMessage*) buildPartial;

- (WelcomeMessageBuilder*) mergeFrom:(WelcomeMessage*) other;
- (WelcomeMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (WelcomeMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDomain;
- (NSString*) domain;
- (WelcomeMessageBuilder*) setDomain:(NSString*) value;
- (WelcomeMessageBuilder*) clearDomain;

- (BOOL) hasVersion;
- (NSString*) version;
- (WelcomeMessageBuilder*) setVersion:(NSString*) value;
- (WelcomeMessageBuilder*) clearVersion;

- (BOOL) hasUser;
- (NSString*) user;
- (WelcomeMessageBuilder*) setUser:(NSString*) value;
- (WelcomeMessageBuilder*) clearUser;

- (BOOL) hasSockmod;
- (NSString*) sockmod;
- (WelcomeMessageBuilder*) setSockmod:(NSString*) value;
- (WelcomeMessageBuilder*) clearSockmod;
@end

#define StreamBegin_domain @"domain"
#define StreamBegin_version @"version"
#define StreamBegin_bodys @"bodys"
@interface StreamBegin : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasDomain_:1;
  BOOL hasVersion_:1;
  NSString* domain;
  NSString* version;
  NSMutableArray * bodysArray;
}
- (BOOL) hasDomain;
- (BOOL) hasVersion;
@property (readonly, strong) NSString* domain;
@property (readonly, strong) NSString* version;
@property (readonly, strong) NSArray<MessageBody*> * bodys;
- (MessageBody*)bodysAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (StreamBeginBuilder*) builder;
+ (StreamBeginBuilder*) builder;
+ (StreamBeginBuilder*) builderWithPrototype:(StreamBegin*) prototype;
- (StreamBeginBuilder*) toBuilder;

+ (StreamBegin*) parseFromData:(NSData*) data;
+ (StreamBegin*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StreamBegin*) parseFromInputStream:(NSInputStream*) input;
+ (StreamBegin*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StreamBegin*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (StreamBegin*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface StreamBeginBuilder : PBGeneratedMessageBuilder {
@private
  StreamBegin* resultStreamBegin;
}

- (StreamBegin*) defaultInstance;

- (StreamBeginBuilder*) clear;
- (StreamBeginBuilder*) clone;

- (StreamBegin*) build;
- (StreamBegin*) buildPartial;

- (StreamBeginBuilder*) mergeFrom:(StreamBegin*) other;
- (StreamBeginBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (StreamBeginBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDomain;
- (NSString*) domain;
- (StreamBeginBuilder*) setDomain:(NSString*) value;
- (StreamBeginBuilder*) clearDomain;

- (BOOL) hasVersion;
- (NSString*) version;
- (StreamBeginBuilder*) setVersion:(NSString*) value;
- (StreamBeginBuilder*) clearVersion;

- (NSMutableArray<MessageBody*> *)bodys;
- (MessageBody*)bodysAtIndex:(NSUInteger)index;
- (StreamBeginBuilder *)addBodys:(MessageBody*)value;
- (StreamBeginBuilder *)setBodysArray:(NSArray<MessageBody*> *)array;
- (StreamBeginBuilder *)clearBodys;
@end

@interface StartTLS : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (StartTLSBuilder*) builder;
+ (StartTLSBuilder*) builder;
+ (StartTLSBuilder*) builderWithPrototype:(StartTLS*) prototype;
- (StartTLSBuilder*) toBuilder;

+ (StartTLS*) parseFromData:(NSData*) data;
+ (StartTLS*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StartTLS*) parseFromInputStream:(NSInputStream*) input;
+ (StartTLS*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StartTLS*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (StartTLS*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface StartTLSBuilder : PBGeneratedMessageBuilder {
@private
  StartTLS* resultStartTls;
}

- (StartTLS*) defaultInstance;

- (StartTLSBuilder*) clear;
- (StartTLSBuilder*) clone;

- (StartTLS*) build;
- (StartTLS*) buildPartial;

- (StartTLSBuilder*) mergeFrom:(StartTLS*) other;
- (StartTLSBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (StartTLSBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProceedTLS : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProceedTLSBuilder*) builder;
+ (ProceedTLSBuilder*) builder;
+ (ProceedTLSBuilder*) builderWithPrototype:(ProceedTLS*) prototype;
- (ProceedTLSBuilder*) toBuilder;

+ (ProceedTLS*) parseFromData:(NSData*) data;
+ (ProceedTLS*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProceedTLS*) parseFromInputStream:(NSInputStream*) input;
+ (ProceedTLS*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProceedTLS*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProceedTLS*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProceedTLSBuilder : PBGeneratedMessageBuilder {
@private
  ProceedTLS* resultProceedTls;
}

- (ProceedTLS*) defaultInstance;

- (ProceedTLSBuilder*) clear;
- (ProceedTLSBuilder*) clone;

- (ProceedTLS*) build;
- (ProceedTLS*) buildPartial;

- (ProceedTLSBuilder*) mergeFrom:(ProceedTLS*) other;
- (ProceedTLSBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProceedTLSBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define StreamEnd_reason @"reason"
#define StreamEnd_code @"code"
@interface StreamEnd : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCode_:1;
  BOOL hasReason_:1;
  SInt32 code;
  NSString* reason;
}
- (BOOL) hasReason;
- (BOOL) hasCode;
@property (readonly, strong) NSString* reason;
@property (readonly) SInt32 code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (StreamEndBuilder*) builder;
+ (StreamEndBuilder*) builder;
+ (StreamEndBuilder*) builderWithPrototype:(StreamEnd*) prototype;
- (StreamEndBuilder*) toBuilder;

+ (StreamEnd*) parseFromData:(NSData*) data;
+ (StreamEnd*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StreamEnd*) parseFromInputStream:(NSInputStream*) input;
+ (StreamEnd*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StreamEnd*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (StreamEnd*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface StreamEndBuilder : PBGeneratedMessageBuilder {
@private
  StreamEnd* resultStreamEnd;
}

- (StreamEnd*) defaultInstance;

- (StreamEndBuilder*) clear;
- (StreamEndBuilder*) clone;

- (StreamEnd*) build;
- (StreamEnd*) buildPartial;

- (StreamEndBuilder*) mergeFrom:(StreamEnd*) other;
- (StreamEndBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (StreamEndBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasReason;
- (NSString*) reason;
- (StreamEndBuilder*) setReason:(NSString*) value;
- (StreamEndBuilder*) clearReason;

- (BOOL) hasCode;
- (SInt32) code;
- (StreamEndBuilder*) setCode:(SInt32) value;
- (StreamEndBuilder*) clearCode;
@end

#define UserConnect_domain @"domain"
#define UserConnect_version @"version"
@interface UserConnect : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasDomain_:1;
  BOOL hasVersion_:1;
  NSString* domain;
  NSString* version;
}
- (BOOL) hasDomain;
- (BOOL) hasVersion;
@property (readonly, strong) NSString* domain;
@property (readonly, strong) NSString* version;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserConnectBuilder*) builder;
+ (UserConnectBuilder*) builder;
+ (UserConnectBuilder*) builderWithPrototype:(UserConnect*) prototype;
- (UserConnectBuilder*) toBuilder;

+ (UserConnect*) parseFromData:(NSData*) data;
+ (UserConnect*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserConnect*) parseFromInputStream:(NSInputStream*) input;
+ (UserConnect*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserConnect*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserConnect*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserConnectBuilder : PBGeneratedMessageBuilder {
@private
  UserConnect* resultUserConnect;
}

- (UserConnect*) defaultInstance;

- (UserConnectBuilder*) clear;
- (UserConnectBuilder*) clone;

- (UserConnect*) build;
- (UserConnect*) buildPartial;

- (UserConnectBuilder*) mergeFrom:(UserConnect*) other;
- (UserConnectBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserConnectBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDomain;
- (NSString*) domain;
- (UserConnectBuilder*) setDomain:(NSString*) value;
- (UserConnectBuilder*) clearDomain;

- (BOOL) hasVersion;
- (NSString*) version;
- (UserConnectBuilder*) setVersion:(NSString*) value;
- (UserConnectBuilder*) clearVersion;
@end

#define Capability_version @"version"
#define Capability_bodys @"bodys"
@interface Capability : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasVersion_:1;
  BOOL hasBodys_:1;
  NSString* version;
  MessageBody* bodys;
}
- (BOOL) hasVersion;
- (BOOL) hasBodys;
@property (readonly, strong) NSString* version;
@property (readonly, strong) MessageBody* bodys;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CapabilityBuilder*) builder;
+ (CapabilityBuilder*) builder;
+ (CapabilityBuilder*) builderWithPrototype:(Capability*) prototype;
- (CapabilityBuilder*) toBuilder;

+ (Capability*) parseFromData:(NSData*) data;
+ (Capability*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Capability*) parseFromInputStream:(NSInputStream*) input;
+ (Capability*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Capability*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Capability*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CapabilityBuilder : PBGeneratedMessageBuilder {
@private
  Capability* resultCapability;
}

- (Capability*) defaultInstance;

- (CapabilityBuilder*) clear;
- (CapabilityBuilder*) clone;

- (Capability*) build;
- (Capability*) buildPartial;

- (CapabilityBuilder*) mergeFrom:(Capability*) other;
- (CapabilityBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CapabilityBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasVersion;
- (NSString*) version;
- (CapabilityBuilder*) setVersion:(NSString*) value;
- (CapabilityBuilder*) clearVersion;

- (BOOL) hasBodys;
- (MessageBody*) bodys;
- (CapabilityBuilder*) setBodys:(MessageBody*) value;
- (CapabilityBuilder*) setBodysBuilder:(MessageBodyBuilder*) builderForValue;
- (CapabilityBuilder*) mergeBodys:(MessageBody*) value;
- (CapabilityBuilder*) clearBodys;
@end

#define ResponseSucceeded_code @"code"
#define ResponseSucceeded_msgId @"msgId"
#define ResponseSucceeded_info @"info"
#define ResponseSucceeded_body @"body"
@interface ResponseSucceeded : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCode_:1;
  BOOL hasMsgId_:1;
  BOOL hasInfo_:1;
  BOOL hasBody_:1;
  SInt32 code;
  NSString* msgId;
  NSString* info;
  MessageBody* body;
}
- (BOOL) hasCode;
- (BOOL) hasMsgId;
- (BOOL) hasInfo;
- (BOOL) hasBody;
@property (readonly) SInt32 code;
@property (readonly, strong) NSString* msgId;
@property (readonly, strong) NSString* info;
@property (readonly, strong) MessageBody* body;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ResponseSucceededBuilder*) builder;
+ (ResponseSucceededBuilder*) builder;
+ (ResponseSucceededBuilder*) builderWithPrototype:(ResponseSucceeded*) prototype;
- (ResponseSucceededBuilder*) toBuilder;

+ (ResponseSucceeded*) parseFromData:(NSData*) data;
+ (ResponseSucceeded*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseSucceeded*) parseFromInputStream:(NSInputStream*) input;
+ (ResponseSucceeded*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseSucceeded*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ResponseSucceeded*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ResponseSucceededBuilder : PBGeneratedMessageBuilder {
@private
  ResponseSucceeded* resultResponseSucceeded;
}

- (ResponseSucceeded*) defaultInstance;

- (ResponseSucceededBuilder*) clear;
- (ResponseSucceededBuilder*) clone;

- (ResponseSucceeded*) build;
- (ResponseSucceeded*) buildPartial;

- (ResponseSucceededBuilder*) mergeFrom:(ResponseSucceeded*) other;
- (ResponseSucceededBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ResponseSucceededBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCode;
- (SInt32) code;
- (ResponseSucceededBuilder*) setCode:(SInt32) value;
- (ResponseSucceededBuilder*) clearCode;

- (BOOL) hasMsgId;
- (NSString*) msgId;
- (ResponseSucceededBuilder*) setMsgId:(NSString*) value;
- (ResponseSucceededBuilder*) clearMsgId;

- (BOOL) hasInfo;
- (NSString*) info;
- (ResponseSucceededBuilder*) setInfo:(NSString*) value;
- (ResponseSucceededBuilder*) clearInfo;

- (BOOL) hasBody;
- (MessageBody*) body;
- (ResponseSucceededBuilder*) setBody:(MessageBody*) value;
- (ResponseSucceededBuilder*) setBodyBuilder:(MessageBodyBuilder*) builderForValue;
- (ResponseSucceededBuilder*) mergeBody:(MessageBody*) value;
- (ResponseSucceededBuilder*) clearBody;
@end

#define ResponseFailure_code @"code"
#define ResponseFailure_msgId @"msgId"
#define ResponseFailure_error @"error"
#define ResponseFailure_body @"body"
@interface ResponseFailure : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCode_:1;
  BOOL hasMsgId_:1;
  BOOL hasError_:1;
  BOOL hasBody_:1;
  SInt32 code;
  NSString* msgId;
  NSString* error;
  MessageBody* body;
}
- (BOOL) hasCode;
- (BOOL) hasMsgId;
- (BOOL) hasError;
- (BOOL) hasBody;
@property (readonly) SInt32 code;
@property (readonly, strong) NSString* msgId;
@property (readonly, strong) NSString* error;
@property (readonly, strong) MessageBody* body;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ResponseFailureBuilder*) builder;
+ (ResponseFailureBuilder*) builder;
+ (ResponseFailureBuilder*) builderWithPrototype:(ResponseFailure*) prototype;
- (ResponseFailureBuilder*) toBuilder;

+ (ResponseFailure*) parseFromData:(NSData*) data;
+ (ResponseFailure*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseFailure*) parseFromInputStream:(NSInputStream*) input;
+ (ResponseFailure*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseFailure*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ResponseFailure*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ResponseFailureBuilder : PBGeneratedMessageBuilder {
@private
  ResponseFailure* resultResponseFailure;
}

- (ResponseFailure*) defaultInstance;

- (ResponseFailureBuilder*) clear;
- (ResponseFailureBuilder*) clone;

- (ResponseFailure*) build;
- (ResponseFailure*) buildPartial;

- (ResponseFailureBuilder*) mergeFrom:(ResponseFailure*) other;
- (ResponseFailureBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ResponseFailureBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCode;
- (SInt32) code;
- (ResponseFailureBuilder*) setCode:(SInt32) value;
- (ResponseFailureBuilder*) clearCode;

- (BOOL) hasMsgId;
- (NSString*) msgId;
- (ResponseFailureBuilder*) setMsgId:(NSString*) value;
- (ResponseFailureBuilder*) clearMsgId;

- (BOOL) hasError;
- (NSString*) error;
- (ResponseFailureBuilder*) setError:(NSString*) value;
- (ResponseFailureBuilder*) clearError;

- (BOOL) hasBody;
- (MessageBody*) body;
- (ResponseFailureBuilder*) setBody:(MessageBody*) value;
- (ResponseFailureBuilder*) setBodyBuilder:(MessageBodyBuilder*) builderForValue;
- (ResponseFailureBuilder*) mergeBody:(MessageBody*) value;
- (ResponseFailureBuilder*) clearBody;
@end

#define ProtoMessage_options @"options"
#define ProtoMessage_signalType @"signalType"
#define ProtoMessage_from @"pb_from"
#define ProtoMessage_to @"to"
#define ProtoMessage_message @"message"
#define ProtoMessage_realfrom @"realfrom"
#define ProtoMessage_realto @"realto"
#define ProtoMessage_originfrom @"originfrom"
#define ProtoMessage_originto @"originto"
#define ProtoMessage_origintype @"origintype"
#define ProtoMessage_sendjid @"sendjid"
@interface ProtoMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOptions_:1;
  BOOL hasSignalType_:1;
  BOOL hasFrom_:1;
  BOOL hasTo_:1;
  BOOL hasRealfrom_:1;
  BOOL hasRealto_:1;
  BOOL hasOriginfrom_:1;
  BOOL hasOriginto_:1;
  BOOL hasOrigintype_:1;
  BOOL hasSendjid_:1;
  BOOL hasMessage_:1;
  SInt32 options;
  SInt32 signalType;
  NSString* pb_from;
  NSString* to;
  NSString* realfrom;
  NSString* realto;
  NSString* originfrom;
  NSString* originto;
  NSString* origintype;
  NSString* sendjid;
  NSData* message;
}
- (BOOL) hasOptions;
- (BOOL) hasSignalType;
- (BOOL) hasFrom;
- (BOOL) hasTo;
- (BOOL) hasMessage;
- (BOOL) hasRealfrom;
- (BOOL) hasRealto;
- (BOOL) hasOriginfrom;
- (BOOL) hasOriginto;
- (BOOL) hasOrigintype;
- (BOOL) hasSendjid;
@property (readonly) SInt32 options;
@property (readonly) SInt32 signalType;
@property (readonly, strong) NSString* pb_from;
@property (readonly, strong) NSString* to;
@property (readonly, strong) NSData* message;
@property (readonly, strong) NSString* realfrom;
@property (readonly, strong) NSString* realto;
@property (readonly, strong) NSString* originfrom;
@property (readonly, strong) NSString* originto;
@property (readonly, strong) NSString* origintype;
@property (readonly, strong) NSString* sendjid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtoMessageBuilder*) builder;
+ (ProtoMessageBuilder*) builder;
+ (ProtoMessageBuilder*) builderWithPrototype:(ProtoMessage*) prototype;
- (ProtoMessageBuilder*) toBuilder;

+ (ProtoMessage*) parseFromData:(NSData*) data;
+ (ProtoMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtoMessage*) parseFromInputStream:(NSInputStream*) input;
+ (ProtoMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtoMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtoMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtoMessageBuilder : PBGeneratedMessageBuilder {
@private
  ProtoMessage* resultProtoMessage;
}

- (ProtoMessage*) defaultInstance;

- (ProtoMessageBuilder*) clear;
- (ProtoMessageBuilder*) clone;

- (ProtoMessage*) build;
- (ProtoMessage*) buildPartial;

- (ProtoMessageBuilder*) mergeFrom:(ProtoMessage*) other;
- (ProtoMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtoMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOptions;
- (SInt32) options;
- (ProtoMessageBuilder*) setOptions:(SInt32) value;
- (ProtoMessageBuilder*) clearOptions;

- (BOOL) hasSignalType;
- (SInt32) signalType;
- (ProtoMessageBuilder*) setSignalType:(SInt32) value;
- (ProtoMessageBuilder*) clearSignalType;

- (BOOL) hasFrom;
- (NSString*) pb_from;
- (ProtoMessageBuilder*) setFrom:(NSString*) value;
- (ProtoMessageBuilder*) clearFrom;

- (BOOL) hasTo;
- (NSString*) to;
- (ProtoMessageBuilder*) setTo:(NSString*) value;
- (ProtoMessageBuilder*) clearTo;

- (BOOL) hasMessage;
- (NSData*) message;
- (ProtoMessageBuilder*) setMessage:(NSData*) value;
- (ProtoMessageBuilder*) clearMessage;

- (BOOL) hasRealfrom;
- (NSString*) realfrom;
- (ProtoMessageBuilder*) setRealfrom:(NSString*) value;
- (ProtoMessageBuilder*) clearRealfrom;

- (BOOL) hasRealto;
- (NSString*) realto;
- (ProtoMessageBuilder*) setRealto:(NSString*) value;
- (ProtoMessageBuilder*) clearRealto;

- (BOOL) hasOriginfrom;
- (NSString*) originfrom;
- (ProtoMessageBuilder*) setOriginfrom:(NSString*) value;
- (ProtoMessageBuilder*) clearOriginfrom;

- (BOOL) hasOriginto;
- (NSString*) originto;
- (ProtoMessageBuilder*) setOriginto:(NSString*) value;
- (ProtoMessageBuilder*) clearOriginto;

- (BOOL) hasOrigintype;
- (NSString*) origintype;
- (ProtoMessageBuilder*) setOrigintype:(NSString*) value;
- (ProtoMessageBuilder*) clearOrigintype;

- (BOOL) hasSendjid;
- (NSString*) sendjid;
- (ProtoMessageBuilder*) setSendjid:(NSString*) value;
- (ProtoMessageBuilder*) clearSendjid;
@end

#define MessageBody_headers @"headers"
#define MessageBody_value @"value"
#define MessageBody_bodys @"bodys"
@interface MessageBody : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasValue_:1;
  NSString* value;
  NSMutableArray * headersArray;
  NSMutableArray * bodysArray;
}
- (BOOL) hasValue;
@property (readonly, strong) NSArray<StringHeader*> * headers;
@property (readonly, strong) NSString* value;
@property (readonly, strong) NSArray<MessageBody*> * bodys;
- (StringHeader*)headersAtIndex:(NSUInteger)index;
- (MessageBody*)bodysAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageBodyBuilder*) builder;
+ (MessageBodyBuilder*) builder;
+ (MessageBodyBuilder*) builderWithPrototype:(MessageBody*) prototype;
- (MessageBodyBuilder*) toBuilder;

+ (MessageBody*) parseFromData:(NSData*) data;
+ (MessageBody*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBody*) parseFromInputStream:(NSInputStream*) input;
+ (MessageBody*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBody*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageBody*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageBodyBuilder : PBGeneratedMessageBuilder {
@private
  MessageBody* resultMessageBody;
}

- (MessageBody*) defaultInstance;

- (MessageBodyBuilder*) clear;
- (MessageBodyBuilder*) clone;

- (MessageBody*) build;
- (MessageBody*) buildPartial;

- (MessageBodyBuilder*) mergeFrom:(MessageBody*) other;
- (MessageBodyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageBodyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray<StringHeader*> *)headers;
- (StringHeader*)headersAtIndex:(NSUInteger)index;
- (MessageBodyBuilder *)addHeaders:(StringHeader*)value;
- (MessageBodyBuilder *)setHeadersArray:(NSArray<StringHeader*> *)array;
- (MessageBodyBuilder *)clearHeaders;

- (BOOL) hasValue;
- (NSString*) value;
- (MessageBodyBuilder*) setValue:(NSString*) value;
- (MessageBodyBuilder*) clearValue;

- (NSMutableArray<MessageBody*> *)bodys;
- (MessageBody*)bodysAtIndex:(NSUInteger)index;
- (MessageBodyBuilder *)addBodys:(MessageBody*)value;
- (MessageBodyBuilder *)setBodysArray:(NSArray<MessageBody*> *)array;
- (MessageBodyBuilder *)clearBodys;
@end

#define IQMessage_namespace @"namespace"
#define IQMessage_key @"key"
#define IQMessage_value @"value"
#define IQMessage_messageId @"messageId"
#define IQMessage_header @"header"
#define IQMessage_body @"body"
#define IQMessage_receivedTime @"receivedTime"
#define IQMessage_transferTime @"transferTime"
#define IQMessage_headers @"headers"
#define IQMessage_bodys @"bodys"
#define IQMessage_definedKey @"definedKey"
@interface IQMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasReceivedTime_:1;
  BOOL hasTransferTime_:1;
  BOOL hasNamespace_:1;
  BOOL hasKey_:1;
  BOOL hasValue_:1;
  BOOL hasMessageId_:1;
  BOOL hasHeader_:1;
  BOOL hasBody_:1;
  BOOL hasDefinedKey_:1;
  SInt64 receivedTime;
  SInt64 transferTime;
  NSString* namespace;
  NSString* key;
  NSString* value;
  NSString* messageId;
  StringHeader* header;
  MessageBody* body;
  IQMessageKeyType definedKey;
  NSMutableArray * headersArray;
  NSMutableArray * bodysArray;
}
- (BOOL) hasNamespace;
- (BOOL) hasKey;
- (BOOL) hasValue;
- (BOOL) hasMessageId;
- (BOOL) hasHeader;
- (BOOL) hasBody;
- (BOOL) hasReceivedTime;
- (BOOL) hasTransferTime;
- (BOOL) hasDefinedKey;
@property (readonly, strong) NSString* namespace;
@property (readonly, strong) NSString* key;
@property (readonly, strong) NSString* value;
@property (readonly, strong) NSString* messageId;
@property (readonly, strong) StringHeader* header;
@property (readonly, strong) MessageBody* body;
@property (readonly) SInt64 receivedTime;
@property (readonly) SInt64 transferTime;
@property (readonly, strong) NSArray<StringHeader*> * headers;
@property (readonly, strong) NSArray<MessageBody*> * bodys;
@property (readonly) IQMessageKeyType definedKey;
- (StringHeader*)headersAtIndex:(NSUInteger)index;
- (MessageBody*)bodysAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IQMessageBuilder*) builder;
+ (IQMessageBuilder*) builder;
+ (IQMessageBuilder*) builderWithPrototype:(IQMessage*) prototype;
- (IQMessageBuilder*) toBuilder;

+ (IQMessage*) parseFromData:(NSData*) data;
+ (IQMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IQMessage*) parseFromInputStream:(NSInputStream*) input;
+ (IQMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IQMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IQMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IQMessageBuilder : PBGeneratedMessageBuilder {
@private
  IQMessage* resultIqmessage;
}

- (IQMessage*) defaultInstance;

- (IQMessageBuilder*) clear;
- (IQMessageBuilder*) clone;

- (IQMessage*) build;
- (IQMessage*) buildPartial;

- (IQMessageBuilder*) mergeFrom:(IQMessage*) other;
- (IQMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IQMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNamespace;
- (NSString*) namespace;
- (IQMessageBuilder*) setNamespace:(NSString*) value;
- (IQMessageBuilder*) clearNamespace;

- (BOOL) hasKey;
- (NSString*) key;
- (IQMessageBuilder*) setKey:(NSString*) value;
- (IQMessageBuilder*) clearKey;

- (BOOL) hasValue;
- (NSString*) value;
- (IQMessageBuilder*) setValue:(NSString*) value;
- (IQMessageBuilder*) clearValue;

- (BOOL) hasMessageId;
- (NSString*) messageId;
- (IQMessageBuilder*) setMessageId:(NSString*) value;
- (IQMessageBuilder*) clearMessageId;

- (BOOL) hasHeader;
- (StringHeader*) header;
- (IQMessageBuilder*) setHeader:(StringHeader*) value;
- (IQMessageBuilder*) setHeaderBuilder:(StringHeaderBuilder*) builderForValue;
- (IQMessageBuilder*) mergeHeader:(StringHeader*) value;
- (IQMessageBuilder*) clearHeader;

- (BOOL) hasBody;
- (MessageBody*) body;
- (IQMessageBuilder*) setBody:(MessageBody*) value;
- (IQMessageBuilder*) setBodyBuilder:(MessageBodyBuilder*) builderForValue;
- (IQMessageBuilder*) mergeBody:(MessageBody*) value;
- (IQMessageBuilder*) clearBody;

- (BOOL) hasReceivedTime;
- (SInt64) receivedTime;
- (IQMessageBuilder*) setReceivedTime:(SInt64) value;
- (IQMessageBuilder*) clearReceivedTime;

- (BOOL) hasTransferTime;
- (SInt64) transferTime;
- (IQMessageBuilder*) setTransferTime:(SInt64) value;
- (IQMessageBuilder*) clearTransferTime;

- (NSMutableArray<StringHeader*> *)headers;
- (StringHeader*)headersAtIndex:(NSUInteger)index;
- (IQMessageBuilder *)addHeaders:(StringHeader*)value;
- (IQMessageBuilder *)setHeadersArray:(NSArray<StringHeader*> *)array;
- (IQMessageBuilder *)clearHeaders;

- (NSMutableArray<MessageBody*> *)bodys;
- (MessageBody*)bodysAtIndex:(NSUInteger)index;
- (IQMessageBuilder *)addBodys:(MessageBody*)value;
- (IQMessageBuilder *)setBodysArray:(NSArray<MessageBody*> *)array;
- (IQMessageBuilder *)clearBodys;

- (BOOL) hasDefinedKey;
- (IQMessageKeyType) definedKey;
- (IQMessageBuilder*) setDefinedKey:(IQMessageKeyType) value;
- (IQMessageBuilder*) clearDefinedKey;
@end

#define PresenceMessage_namespace @"namespace"
#define PresenceMessage_key @"key"
#define PresenceMessage_value @"value"
#define PresenceMessage_messageId @"messageId"
#define PresenceMessage_header @"header"
#define PresenceMessage_body @"body"
#define PresenceMessage_receivedTime @"receivedTime"
#define PresenceMessage_transferTime @"transferTime"
#define PresenceMessage_headers @"headers"
#define PresenceMessage_bodys @"bodys"
#define PresenceMessage_definedKey @"definedKey"
#define PresenceMessage_categoryType @"categoryType"
@interface PresenceMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasReceivedTime_:1;
  BOOL hasTransferTime_:1;
  BOOL hasCategoryType_:1;
  BOOL hasNamespace_:1;
  BOOL hasKey_:1;
  BOOL hasValue_:1;
  BOOL hasMessageId_:1;
  BOOL hasHeader_:1;
  BOOL hasBody_:1;
  BOOL hasDefinedKey_:1;
  SInt64 receivedTime;
  SInt64 transferTime;
  SInt32 categoryType;
  NSString* namespace;
  NSString* key;
  NSString* value;
  NSString* messageId;
  StringHeader* header;
  MessageBody* body;
  PresenceKeyType definedKey;
  NSMutableArray * headersArray;
  NSMutableArray * bodysArray;
}
- (BOOL) hasNamespace;
- (BOOL) hasKey;
- (BOOL) hasValue;
- (BOOL) hasMessageId;
- (BOOL) hasHeader;
- (BOOL) hasBody;
- (BOOL) hasReceivedTime;
- (BOOL) hasTransferTime;
- (BOOL) hasDefinedKey;
- (BOOL) hasCategoryType;
@property (readonly, strong) NSString* namespace;
@property (readonly, strong) NSString* key;
@property (readonly, strong) NSString* value;
@property (readonly, strong) NSString* messageId;
@property (readonly, strong) StringHeader* header;
@property (readonly, strong) MessageBody* body;
@property (readonly) SInt64 receivedTime;
@property (readonly) SInt64 transferTime;
@property (readonly, strong) NSArray<StringHeader*> * headers;
@property (readonly, strong) NSArray<MessageBody*> * bodys;
@property (readonly) PresenceKeyType definedKey;
@property (readonly) SInt32 categoryType;
- (StringHeader*)headersAtIndex:(NSUInteger)index;
- (MessageBody*)bodysAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PresenceMessageBuilder*) builder;
+ (PresenceMessageBuilder*) builder;
+ (PresenceMessageBuilder*) builderWithPrototype:(PresenceMessage*) prototype;
- (PresenceMessageBuilder*) toBuilder;

+ (PresenceMessage*) parseFromData:(NSData*) data;
+ (PresenceMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PresenceMessage*) parseFromInputStream:(NSInputStream*) input;
+ (PresenceMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PresenceMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PresenceMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PresenceMessageBuilder : PBGeneratedMessageBuilder {
@private
  PresenceMessage* resultPresenceMessage;
}

- (PresenceMessage*) defaultInstance;

- (PresenceMessageBuilder*) clear;
- (PresenceMessageBuilder*) clone;

- (PresenceMessage*) build;
- (PresenceMessage*) buildPartial;

- (PresenceMessageBuilder*) mergeFrom:(PresenceMessage*) other;
- (PresenceMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PresenceMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNamespace;
- (NSString*) namespace;
- (PresenceMessageBuilder*) setNamespace:(NSString*) value;
- (PresenceMessageBuilder*) clearNamespace;

- (BOOL) hasKey;
- (NSString*) key;
- (PresenceMessageBuilder*) setKey:(NSString*) value;
- (PresenceMessageBuilder*) clearKey;

- (BOOL) hasValue;
- (NSString*) value;
- (PresenceMessageBuilder*) setValue:(NSString*) value;
- (PresenceMessageBuilder*) clearValue;

- (BOOL) hasMessageId;
- (NSString*) messageId;
- (PresenceMessageBuilder*) setMessageId:(NSString*) value;
- (PresenceMessageBuilder*) clearMessageId;

- (BOOL) hasHeader;
- (StringHeader*) header;
- (PresenceMessageBuilder*) setHeader:(StringHeader*) value;
- (PresenceMessageBuilder*) setHeaderBuilder:(StringHeaderBuilder*) builderForValue;
- (PresenceMessageBuilder*) mergeHeader:(StringHeader*) value;
- (PresenceMessageBuilder*) clearHeader;

- (BOOL) hasBody;
- (MessageBody*) body;
- (PresenceMessageBuilder*) setBody:(MessageBody*) value;
- (PresenceMessageBuilder*) setBodyBuilder:(MessageBodyBuilder*) builderForValue;
- (PresenceMessageBuilder*) mergeBody:(MessageBody*) value;
- (PresenceMessageBuilder*) clearBody;

- (BOOL) hasReceivedTime;
- (SInt64) receivedTime;
- (PresenceMessageBuilder*) setReceivedTime:(SInt64) value;
- (PresenceMessageBuilder*) clearReceivedTime;

- (BOOL) hasTransferTime;
- (SInt64) transferTime;
- (PresenceMessageBuilder*) setTransferTime:(SInt64) value;
- (PresenceMessageBuilder*) clearTransferTime;

- (NSMutableArray<StringHeader*> *)headers;
- (StringHeader*)headersAtIndex:(NSUInteger)index;
- (PresenceMessageBuilder *)addHeaders:(StringHeader*)value;
- (PresenceMessageBuilder *)setHeadersArray:(NSArray<StringHeader*> *)array;
- (PresenceMessageBuilder *)clearHeaders;

- (NSMutableArray<MessageBody*> *)bodys;
- (MessageBody*)bodysAtIndex:(NSUInteger)index;
- (PresenceMessageBuilder *)addBodys:(MessageBody*)value;
- (PresenceMessageBuilder *)setBodysArray:(NSArray<MessageBody*> *)array;
- (PresenceMessageBuilder *)clearBodys;

- (BOOL) hasDefinedKey;
- (PresenceKeyType) definedKey;
- (PresenceMessageBuilder*) setDefinedKey:(PresenceKeyType) value;
- (PresenceMessageBuilder*) clearDefinedKey;

- (BOOL) hasCategoryType;
- (SInt32) categoryType;
- (PresenceMessageBuilder*) setCategoryType:(SInt32) value;
- (PresenceMessageBuilder*) clearCategoryType;
@end

#define XmppMessage_messageType @"messageType"
#define XmppMessage_clientType @"clientType"
#define XmppMessage_clientVersion @"clientVersion"
#define XmppMessage_namespace @"namespace"
#define XmppMessage_key @"key"
#define XmppMessage_value @"value"
#define XmppMessage_messageId @"messageId"
#define XmppMessage_header @"header"
#define XmppMessage_body @"body"
#define XmppMessage_receivedTime @"receivedTime"
#define XmppMessage_transferTime @"transferTime"
#define XmppMessage_headers @"headers"
#define XmppMessage_bodys @"bodys"
@interface XmppMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasClientVersion_:1;
  BOOL hasReceivedTime_:1;
  BOOL hasTransferTime_:1;
  BOOL hasMessageType_:1;
  BOOL hasClientType_:1;
  BOOL hasNamespace_:1;
  BOOL hasKey_:1;
  BOOL hasValue_:1;
  BOOL hasMessageId_:1;
  BOOL hasHeader_:1;
  BOOL hasBody_:1;
  SInt64 clientVersion;
  SInt64 receivedTime;
  SInt64 transferTime;
  SInt32 messageType;
  SInt32 clientType;
  NSString* namespace;
  NSString* key;
  NSString* value;
  NSString* messageId;
  StringHeader* header;
  MessageBody* body;
  NSMutableArray * headersArray;
  NSMutableArray * bodysArray;
}
- (BOOL) hasMessageType;
- (BOOL) hasClientType;
- (BOOL) hasClientVersion;
- (BOOL) hasNamespace;
- (BOOL) hasKey;
- (BOOL) hasValue;
- (BOOL) hasMessageId;
- (BOOL) hasHeader;
- (BOOL) hasBody;
- (BOOL) hasReceivedTime;
- (BOOL) hasTransferTime;
@property (readonly) SInt32 messageType;
@property (readonly) SInt32 clientType;
@property (readonly) SInt64 clientVersion;
@property (readonly, strong) NSString* namespace;
@property (readonly, strong) NSString* key;
@property (readonly, strong) NSString* value;
@property (readonly, strong) NSString* messageId;
@property (readonly, strong) StringHeader* header;
@property (readonly, strong) MessageBody* body;
@property (readonly) SInt64 receivedTime;
@property (readonly) SInt64 transferTime;
@property (readonly, strong) NSArray<StringHeader*> * headers;
@property (readonly, strong) NSArray<MessageBody*> * bodys;
- (StringHeader*)headersAtIndex:(NSUInteger)index;
- (MessageBody*)bodysAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XmppMessageBuilder*) builder;
+ (XmppMessageBuilder*) builder;
+ (XmppMessageBuilder*) builderWithPrototype:(XmppMessage*) prototype;
- (XmppMessageBuilder*) toBuilder;

+ (XmppMessage*) parseFromData:(NSData*) data;
+ (XmppMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XmppMessage*) parseFromInputStream:(NSInputStream*) input;
+ (XmppMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XmppMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XmppMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XmppMessageBuilder : PBGeneratedMessageBuilder {
@private
  XmppMessage* resultXmppMessage;
}

- (XmppMessage*) defaultInstance;

- (XmppMessageBuilder*) clear;
- (XmppMessageBuilder*) clone;

- (XmppMessage*) build;
- (XmppMessage*) buildPartial;

- (XmppMessageBuilder*) mergeFrom:(XmppMessage*) other;
- (XmppMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XmppMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMessageType;
- (SInt32) messageType;
- (XmppMessageBuilder*) setMessageType:(SInt32) value;
- (XmppMessageBuilder*) clearMessageType;

- (BOOL) hasClientType;
- (SInt32) clientType;
- (XmppMessageBuilder*) setClientType:(SInt32) value;
- (XmppMessageBuilder*) clearClientType;

- (BOOL) hasClientVersion;
- (SInt64) clientVersion;
- (XmppMessageBuilder*) setClientVersion:(SInt64) value;
- (XmppMessageBuilder*) clearClientVersion;

- (BOOL) hasNamespace;
- (NSString*) namespace;
- (XmppMessageBuilder*) setNamespace:(NSString*) value;
- (XmppMessageBuilder*) clearNamespace;

- (BOOL) hasKey;
- (NSString*) key;
- (XmppMessageBuilder*) setKey:(NSString*) value;
- (XmppMessageBuilder*) clearKey;

- (BOOL) hasValue;
- (NSString*) value;
- (XmppMessageBuilder*) setValue:(NSString*) value;
- (XmppMessageBuilder*) clearValue;

- (BOOL) hasMessageId;
- (NSString*) messageId;
- (XmppMessageBuilder*) setMessageId:(NSString*) value;
- (XmppMessageBuilder*) clearMessageId;

- (BOOL) hasHeader;
- (StringHeader*) header;
- (XmppMessageBuilder*) setHeader:(StringHeader*) value;
- (XmppMessageBuilder*) setHeaderBuilder:(StringHeaderBuilder*) builderForValue;
- (XmppMessageBuilder*) mergeHeader:(StringHeader*) value;
- (XmppMessageBuilder*) clearHeader;

- (BOOL) hasBody;
- (MessageBody*) body;
- (XmppMessageBuilder*) setBody:(MessageBody*) value;
- (XmppMessageBuilder*) setBodyBuilder:(MessageBodyBuilder*) builderForValue;
- (XmppMessageBuilder*) mergeBody:(MessageBody*) value;
- (XmppMessageBuilder*) clearBody;

- (BOOL) hasReceivedTime;
- (SInt64) receivedTime;
- (XmppMessageBuilder*) setReceivedTime:(SInt64) value;
- (XmppMessageBuilder*) clearReceivedTime;

- (BOOL) hasTransferTime;
- (SInt64) transferTime;
- (XmppMessageBuilder*) setTransferTime:(SInt64) value;
- (XmppMessageBuilder*) clearTransferTime;

- (NSMutableArray<StringHeader*> *)headers;
- (StringHeader*)headersAtIndex:(NSUInteger)index;
- (XmppMessageBuilder *)addHeaders:(StringHeader*)value;
- (XmppMessageBuilder *)setHeadersArray:(NSArray<StringHeader*> *)array;
- (XmppMessageBuilder *)clearHeaders;

- (NSMutableArray<MessageBody*> *)bodys;
- (MessageBody*)bodysAtIndex:(NSUInteger)index;
- (XmppMessageBuilder *)addBodys:(MessageBody*)value;
- (XmppMessageBuilder *)setBodysArray:(NSArray<MessageBody*> *)array;
- (XmppMessageBuilder *)clearBodys;
@end


// @@protoc_insertion_point(global_scope)
